SELECT 
		I.NAME,  
		CONCAT(I.QUANTITY,' ',I.METRIC) AS QUANTITY,
		CASE WHEN  I.QUANTITY = 0 THEN 'NONE'
			WHEN I.QUANTITY < MIN_QUANTITY THEN 'LOW'
            WHEN I.LAST_UPDATED_DATE <SUBDATE(SYSDATE(),7) THEN 'Not Moving'
         ELSE 'OK'
        
        END AS STATUS

 FROM INVENTORY I

